fix(android): changed from SegmentedControlIOS to SegmentedControlTab
monicahq/old_mobile_app pull request #166
Opened 2018-04-10 19:34 UTC by sfeu

Changed to SegmentedControlTab (MIT License), which also works with Android

2018-04-10 23:32 UTC, Mokto requested changes

2018-04-10 23:32 UTC, Mokto commented on src/pages/Contact/ContactInfos/ContactInfos.tsx
> +    this.setState({index: index});
You could use object literal shorthand. Have you installed tslint in your IDE ?

2018-04-10 23:32 UTC, Mokto commented on src/pages/Contact/ContactInfos/ContactInfos.tsx
> +//        onChange={this.setSegmentedControlState}
You could remove this comment.

2018-04-10 23:32 UTC, Mokto commented on src/pages/Contact/ContactInfos/ContactInfos.tsx
> + //       tintColor={primaryColor}
We need to use the right color for the segmented control tab ;)

2018-04-10 23:32 UTC, Mokto commented
Hi @sfeu,

Thanks ! You are officially the first side contributor to chandler ! It makes us really happy ;)

I made some comments on your code.

2018-04-11 20:01 UTC, sfeu commented
Hi @Mokto,

thanks for your support! I tried to implement the requested changes.

2018-04-12 23:12 UTC, merged

2018-04-12 23:12 UTC, Mokto commented
Thanks @sfeu !